package com.prismorbit.app

import com.google.gson.Gson
import com.google.gson.JsonObject
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import java.io.IOException
import java.net.SocketTimeoutException
import java.net.UnknownHostException
import java.util.concurrent.TimeUnit

// ============================================================
// AI CHAT SERVICE
// ============================================================
// Talks to the AI provider selected by the current user,
// using that user's own API key.
//
// Supported providers:
// Gemini, OpenAI, Anthropic, Perplexity and Grok.
//
// Features:
// - BYOK
// - PRISM grounding context
// - Conversation history
// - Automatic retry for temporary server failures
// - Network calls always run on Dispatchers.IO
// ============================================================

object AiChatService {

    // ========================================================
    // SMART AI PERSONA
    // ========================================================

    private val SYSTEM_PERSONA = """
        You are Smart AI, a helpful assistant inside PRISM Orbit, an academic and
        career-development app for college students. Below is the student's REAL,
        current PRISM data, generated by PRISM's own systems — treat every fact
        in it as ground truth.

        NEVER invent, guess, estimate, or override:
        - a placement readiness score, priority number, or category
        - an academic event, exam, viva, test, or deadline
        - a DSA statistic, project progress, or internship count
        - any date or fact not explicitly present in the data below

        If asked about something not in the data below, say plainly:
        "I don't see that in your PRISM data." Do not guess.

        Be warm, direct and practical — like a good mentor, not a generic chatbot.
        Keep responses reasonably concise unless the student asks for detail.
    """.trimIndent()

    // ========================================================
    // HTTP CLIENT
    // ========================================================

    private val client =
        OkHttpClient.Builder()
            .connectTimeout(
                30,
                TimeUnit.SECONDS
            )
            .readTimeout(
                90,
                TimeUnit.SECONDS
            )
            .writeTimeout(
                30,
                TimeUnit.SECONDS
            )
            .build()

    private val gson = Gson()

    private val jsonMediaType =
        "application/json".toMediaType()

    // ========================================================
    // RETRY CONFIGURATION
    // ========================================================
    //
    // These are temporary server/network failures.
    //
    // 500 = Internal Server Error
    // 502 = Bad Gateway
    // 503 = Service Unavailable
    // 504 = Gateway Timeout
    //
    // We retry these automatically because they can recover
    // without the user changing anything.
    //
    // 429 is deliberately NOT included here because it can
    // mean the user's quota/rate limit is actually exhausted.
    // ========================================================

    private const val MAX_RETRY_ATTEMPTS = 3

    private val RETRY_DELAYS_MS =
        longArrayOf(
            1000L,
            2000L
        )

    // ========================================================
    // PUBLIC SEND MESSAGE
    // ========================================================

    suspend fun sendMessage(
        provider: AiProvider,
        apiKey: String,
        history: List<ChatTurn>,
        newUserMessage: String,
        prismContext: PrismAiContext
    ): Result<String> {

        if (apiKey.isBlank()) {

            return Result.failure(
                IllegalStateException(
                    "Smart AI isn't configured yet — missing API key."
                )
            )
        }

        val systemText =
            SYSTEM_PERSONA +
                    "\n\n" +
                    prismContext.toPromptText()

        return try {

            val replyText =
                when (provider) {

                    // ========================================
                    // GEMINI
                    // ========================================

                    AiProvider.GEMINI -> {

                        callGemini(
                            apiKey = apiKey,
                            systemText = systemText,
                            history = history,
                            newUserMessage = newUserMessage
                        )
                    }

                    // ========================================
                    // OPENAI
                    // ========================================

                    AiProvider.OPENAI -> {

                        callOpenAiCompatible(
                            baseUrl =
                                "https://api.openai.com/v1/chat/completions",
                            apiKey = apiKey,
                            model = provider.defaultModel,
                            systemText = systemText,
                            history = history,
                            newUserMessage = newUserMessage
                        )
                    }

                    // ========================================
                    // PERPLEXITY
                    // ========================================

                    AiProvider.PERPLEXITY -> {

                        callOpenAiCompatible(
                            baseUrl =
                                "https://api.perplexity.ai/chat/completions",
                            apiKey = apiKey,
                            model = provider.defaultModel,
                            systemText = systemText,
                            history = history,
                            newUserMessage = newUserMessage
                        )
                    }

                    // ========================================
                    // GROK
                    // ========================================

                    AiProvider.GROK -> {

                        callOpenAiCompatible(
                            baseUrl =
                                "https://api.x.ai/v1/chat/completions",
                            apiKey = apiKey,
                            model = provider.defaultModel,
                            systemText = systemText,
                            history = history,
                            newUserMessage = newUserMessage
                        )
                    }

                    // ========================================
                    // ANTHROPIC
                    // ========================================

                    AiProvider.ANTHROPIC -> {

                        callAnthropic(
                            apiKey = apiKey,
                            model = provider.defaultModel,
                            systemText = systemText,
                            history = history,
                            newUserMessage = newUserMessage
                        )
                    }
                }

            if (replyText.isNullOrBlank()) {

                Result.failure(
                    Exception(
                        "Smart AI didn't return a response — try again in a moment."
                    )
                )

            } else {

                Result.success(
                    replyText.trim()
                )
            }

        } catch (e: CancellationException) {

            // Never convert coroutine cancellation into a
            // normal AI error.
            throw e

        } catch (e: Exception) {

            Result.failure(
                Exception(
                    friendlyErrorMessage(e)
                )
            )
        }
    }

    // ========================================================
    // GEMINI
    // ========================================================

    private suspend fun callGemini(
        apiKey: String,
        systemText: String,
        history: List<ChatTurn>,
        newUserMessage: String
    ): String? {

        val contents =
            history.map { turn ->

                mapOf(
                    "role" to turn.role,
                    "parts" to listOf(
                        mapOf(
                            "text" to turn.text
                        )
                    )
                )
            } +
                    mapOf(
                        "role" to "user",
                        "parts" to listOf(
                            mapOf(
                                "text" to newUserMessage
                            )
                        )
                    )

        val body =
            mapOf(
                "systemInstruction" to
                        mapOf(
                            "parts" to listOf(
                                mapOf(
                                    "text" to systemText
                                )
                            )
                        ),
                "contents" to contents
            )

        val request =
            Request.Builder()
                .url(
                    "https://generativelanguage.googleapis.com/v1beta/models/${AiProvider.GEMINI.defaultModel}:generateContent"
                )
                .addHeader(
                    "x-goog-api-key",
                    apiKey
                )
                .post(
                    gson.toJson(body)
                        .toRequestBody(
                            jsonMediaType
                        )
                )
                .build()

        val json =
            executeAndParseWithRetry(
                request
            )

        return json
            ?.getAsJsonArray(
                "candidates"
            )
            ?.get(0)
            ?.asJsonObject
            ?.getAsJsonObject(
                "content"
            )
            ?.getAsJsonArray(
                "parts"
            )
            ?.get(0)
            ?.asJsonObject
            ?.get(
                "text"
            )
            ?.asString
    }

    // ========================================================
    // OPENAI-COMPATIBLE PROVIDERS
    // ========================================================
    //
    // Used by:
    // - OpenAI
    // - Perplexity
    // - Grok
    // ========================================================

    private suspend fun callOpenAiCompatible(
        baseUrl: String,
        apiKey: String,
        model: String,
        systemText: String,
        history: List<ChatTurn>,
        newUserMessage: String
    ): String? {

        val messages =
            mutableListOf<Map<String, String>>()

        messages.add(
            mapOf(
                "role" to "system",
                "content" to systemText
            )
        )

        history.forEach { turn ->

            val role =
                if (turn.role == "model") {
                    "assistant"
                } else {
                    "user"
                }

            messages.add(
                mapOf(
                    "role" to role,
                    "content" to turn.text
                )
            )
        }

        messages.add(
            mapOf(
                "role" to "user",
                "content" to newUserMessage
            )
        )

        val body =
            mapOf(
                "model" to model,
                "messages" to messages
            )

        val request =
            Request.Builder()
                .url(baseUrl)
                .addHeader(
                    "Authorization",
                    "Bearer $apiKey"
                )
                .post(
                    gson.toJson(body)
                        .toRequestBody(
                            jsonMediaType
                        )
                )
                .build()

        val json =
            executeAndParseWithRetry(
                request
            )

        return json
            ?.getAsJsonArray(
                "choices"
            )
            ?.get(0)
            ?.asJsonObject
            ?.getAsJsonObject(
                "message"
            )
            ?.get(
                "content"
            )
            ?.asString
    }

    // ========================================================
    // ANTHROPIC
    // ========================================================

    private suspend fun callAnthropic(
        apiKey: String,
        model: String,
        systemText: String,
        history: List<ChatTurn>,
        newUserMessage: String
    ): String? {

        val messages =
            mutableListOf<Map<String, String>>()

        history.forEach { turn ->

            val role =
                if (turn.role == "model") {
                    "assistant"
                } else {
                    "user"
                }

            messages.add(
                mapOf(
                    "role" to role,
                    "content" to turn.text
                )
            )
        }

        messages.add(
            mapOf(
                "role" to "user",
                "content" to newUserMessage
            )
        )

        val body =
            mapOf(
                "model" to model,
                "max_tokens" to 1024,
                "system" to systemText,
                "messages" to messages
            )

        val request =
            Request.Builder()
                .url(
                    "https://api.anthropic.com/v1/messages"
                )
                .addHeader(
                    "x-api-key",
                    apiKey
                )
                .addHeader(
                    "anthropic-version",
                    "2023-06-01"
                )
                .post(
                    gson.toJson(body)
                        .toRequestBody(
                            jsonMediaType
                        )
                )
                .build()

        val json =
            executeAndParseWithRetry(
                request
            )

        return json
            ?.getAsJsonArray(
                "content"
            )
            ?.get(0)
            ?.asJsonObject
            ?.get(
                "text"
            )
            ?.asString
    }

    // ========================================================
    // HTTP EXECUTION + AUTOMATIC RETRY
    // ========================================================

    private suspend fun executeAndParseWithRetry(
        request: Request
    ): JsonObject? {

        var attempt = 1

        while (
            attempt <= MAX_RETRY_ATTEMPTS
        ) {

            try {

                return executeAndParse(
                    request
                )

            } catch (e: AiApiException) {

                // --------------------------------------------
                // TEMPORARY SERVER FAILURE
                // --------------------------------------------

                if (
                    e.code in
                    setOf(
                        500,
                        502,
                        503,
                        504
                    ) &&
                    attempt < MAX_RETRY_ATTEMPTS
                ) {

                    delay(
                        RETRY_DELAYS_MS[
                            attempt - 1
                        ]
                    )

                    attempt++

                    continue
                }

                throw e

            } catch (e: SocketTimeoutException) {

                // --------------------------------------------
                // TEMPORARY TIMEOUT
                // --------------------------------------------

                if (
                    attempt < MAX_RETRY_ATTEMPTS
                ) {

                    delay(
                        RETRY_DELAYS_MS[
                            attempt - 1
                        ]
                    )

                    attempt++

                    continue
                }

                throw e

            } catch (e: IOException) {

                // --------------------------------------------
                // TEMPORARY NETWORK FAILURE
                // --------------------------------------------

                if (
                    e !is UnknownHostException &&
                    attempt < MAX_RETRY_ATTEMPTS
                ) {

                    delay(
                        RETRY_DELAYS_MS[
                            attempt - 1
                        ]
                    )

                    attempt++

                    continue
                }

                throw e
            }
        }

        throw IllegalStateException(
            "Smart AI request failed."
        )
    }

    // ========================================================
    // SINGLE HTTP REQUEST
    // ========================================================
    //
    // IMPORTANT:
    // OkHttp's execute() is blocking.
    // Therefore it MUST run on Dispatchers.IO.
    // ========================================================

    private suspend fun executeAndParse(
        request: Request
    ): JsonObject? {

        return withContext(
            Dispatchers.IO
        ) {

            client
                .newCall(request)
                .execute()
                .use { response ->

                    val bodyString =
                        response.body?.string()

                    if (!response.isSuccessful) {

                        throw AiApiException(
                            code = response.code,
                            responseBody = bodyString
                        )
                    }

                    if (
                        bodyString.isNullOrBlank()
                    ) {

                        return@withContext null
                    }

                    gson.fromJson(
                        bodyString,
                        JsonObject::class.java
                    )
                }
        }
    }

    // ========================================================
    // FRIENDLY ERROR MESSAGES
    // ========================================================

    private fun friendlyErrorMessage(
        e: Exception
    ): String {

        return when {

            e is UnknownHostException ->

                "No internet connection — check your connection and try again."

            e is SocketTimeoutException ->

                "Smart AI took too long to respond — try again."

            e is AiApiException &&
                    e.code == 429 ->

                "Smart AI rate limit or quota reached — try another API key or provider."

            e is AiApiException &&
                    (
                            e.code == 401 ||
                                    e.code == 403
                            ) ->

                "Smart AI couldn't authenticate — the API key may be invalid."

            e is AiApiException &&
                    (
                            e.code == 500 ||
                                    e.code == 502 ||
                                    e.code == 503 ||
                                    e.code == 504
                            ) ->

                "AI provider is temporarily unavailable — Smart AI already retried. Please try again in a moment."

            e is AiApiException ->

                "Smart AI's server returned an error (code ${e.code}) — try again in a moment."

            e is IOException ->

                "Network connection interrupted — please try again."

            else ->

                e.message
                    ?: "Something went wrong — try again in a moment."
        }
    }

    // ========================================================
    // API EXCEPTION
    // ========================================================

    private class AiApiException(
        val code: Int,
        val responseBody: String? = null
    ) : Exception()
}