package com.prismorbit.app

import okhttp3.OkHttpClient
import okhttp3.logging.HttpLoggingInterceptor
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory
import retrofit2.http.Body
import retrofit2.http.POST
import retrofit2.http.Path
import retrofit2.http.Header
import java.util.concurrent.TimeUnit

// ============================================================
// GEMINI CHAT SERVICE
// ============================================================
//
// Sends the conversation so far + PRISM context to Gemini and
// returns the reply as plain text. This is free-form conversation
// (no responseSchema) — unlike GeminiSmartAiEnhancer.kt, which
// forces structured JSON for the dashboard card.
//
// The PRISM context (built by PrismContextBuilder) is sent as a
// systemInstruction — it's the model's grounding, refreshed each
// message, and the model is explicitly told not to override it.
// ============================================================

data class ChatTurn(
    val role: String, // "user" or "model"
    val text: String
)

private data class GeminiChatRequest(
    val systemInstruction: SystemInstruction,
    val contents: List<ChatContent>
)

private data class SystemInstruction(
    val parts: List<ChatPart>
)

private data class ChatContent(
    val role: String,
    val parts: List<ChatPart>
)

private data class ChatPart(
    val text: String
)

private data class GeminiChatResponse(
    val candidates: List<ChatCandidate>?
)

private data class ChatCandidate(
    val content: ChatContent?
)

private interface GeminiChatApiService {

    @POST("v1beta/models/{model}:generateContent")
    suspend fun generateContent(
        @Path("model") model: String = "gemini-3.6-flash",
        @Header("x-goog-api-key") apiKey: String,
        @Body request: GeminiChatRequest
    ): GeminiChatResponse
}

private object GeminiChatNetwork {

    private val logging = HttpLoggingInterceptor().apply {
        level = HttpLoggingInterceptor.Level.BASIC
    }

    private val client = OkHttpClient.Builder()
        .addInterceptor(logging)
        .connectTimeout(30, TimeUnit.SECONDS)
        .readTimeout(90, TimeUnit.SECONDS)
        .build()

    private val retrofit = Retrofit.Builder()
        .baseUrl("https://generativelanguage.googleapis.com/")
        .client(client)
        .addConverterFactory(GsonConverterFactory.create())
        .build()

    val service: GeminiChatApiService =
        retrofit.create(GeminiChatApiService::class.java)
}

object GeminiChatService {

    private const val SYSTEM_PERSONA = """
        You are Smart AI, a helpful assistant inside PRISM Orbit, an academic and
        career-development app for college students. Below is the student's REAL,
        current PRISM data, generated by PRISM's own systems — treat every fact
        in it as ground truth.

        NEVER invent, guess, estimate, or override:
        - a placement readiness score, priority number, or category (these come
          only from PRISM's own scoring engine)
        - an academic event, exam, viva, test, or deadline
        - a DSA statistic (count, difficulty breakdown, or progress percentage)
        - project progress, status, or count
        - internship count or status
        - any date not explicitly present in the data below
        - any other user-specific fact not explicitly present in the data below

        If the student asks about something not present in the data below, say
        plainly: "I don't see that in your PRISM data." Do not guess, estimate,
        or infer a plausible-sounding answer to fill the gap.

        When giving advice or a plan, clearly separate three things in your own
        reasoning (you don't need to label them explicitly in every reply, but
        never blur them together):
        - PRISM FACT: a number or event exactly as given below
        - AI REASONING: your interpretation of why that fact matters right now
        - AI RECOMMENDATION: your suggested action
        Never present your own recommendation as if it were a PRISM fact.

        If asked for a structured report using specific headers (e.g. HIGH
        PRIORITY / MEDIUM PRIORITY / OPTIONAL), follow that exact format rather
        than writing free-form prose. If a category has nothing relevant in the
        real data, say so plainly instead of inventing filler.

        When asked to create a time-based plan, only use real events, deadlines,
        or progress data provided below. If there isn't enough concrete PRISM
        data to fill the requested time, say so plainly rather than inventing
        filler tasks.

        Be warm, direct and practical — like a good mentor, not a generic
        chatbot. Keep responses reasonably concise unless the student asks for
        detail. If asked "why" about a recommendation, explain using the reason
        given below.
    """

    suspend fun sendMessage(
        history: List<ChatTurn>,
        newUserMessage: String,
        prismContext: PrismAiContext,
        apiKey: String
    ): Result<String> {

        if (apiKey.isBlank()) {
            return Result.failure(
                IllegalStateException(
                    "Smart AI isn't configured yet — missing API key."
                )
            )
        }

        return try {

            val systemText =
                SYSTEM_PERSONA.trimIndent() +
                        "\n\n" +
                        prismContext.toPromptText()

            val contents =
                history.map { turn ->
                    ChatContent(
                        role = turn.role,
                        parts = listOf(
                            ChatPart(
                                text = turn.text
                            )
                        )
                    )
                } +
                        ChatContent(
                            role = "user",
                            parts = listOf(
                                ChatPart(
                                    text = newUserMessage
                                )
                            )
                        )

            val request = GeminiChatRequest(
                systemInstruction = SystemInstruction(
                    parts = listOf(
                        ChatPart(
                            text = systemText
                        )
                    )
                ),
                contents = contents
            )

            val response =
                GeminiChatNetwork.service.generateContent(
                    apiKey = apiKey,
                    request = request
                )

            val replyText =
                response.candidates
                    ?.firstOrNull()
                    ?.content
                    ?.parts
                    ?.firstOrNull()
                    ?.text

            if (replyText.isNullOrBlank()) {

                Result.failure(
                    Exception(
                        "Smart AI didn't return a response — try again in a moment."
                    )
                )

            } else {

                Result.success(replyText)
            }

        } catch (e: Exception) {

            Result.failure(
                Exception(
                    friendlyErrorMessage(e)
                )
            )
        }
    }

    // ============================================================
    // PHASE 11 — friendly, classified error messages
    // ============================================================
    // Order matters: more specific exception types are checked before
    // their broader parent types (e.g. SocketTimeoutException is-a
    // IOException, so it must be checked first or it would never be
    // reached).
    // ============================================================
    private fun friendlyErrorMessage(e: Exception): String {
        return when {
            e is java.net.UnknownHostException ->
                "No internet connection — check your connection and try again."

            e is java.net.SocketTimeoutException ->
                "Smart AI took too long to respond — try again."

            e is retrofit2.HttpException && e.code() == 429 ->
                "Smart AI is temporarily busy (rate limit reached) — try again in a moment."

            e is retrofit2.HttpException &&
                    (e.code() == 401 || e.code() == 403) ->
                "Smart AI couldn't authenticate with Gemini — the API key may be invalid."

            e is retrofit2.HttpException ->
                "Smart AI's server returned an error (code ${e.code()}) — try again in a moment."

            e is java.io.IOException ->
                "No internet connection — check your connection and try again."

            else ->
                e.message ?: "Something went wrong — try again in a moment."
        }
    }
}